function C_D_BT = C_D_BT(M,Geometry)

boattail_anlge = atan((0.5*(Geometry.rb_d-Geometry.b_d))/Geometry.bt_l);
cylinder_length = Geometry.t_l - Geometry.n_l;
gamma = 0.85;
tau = (1-Geometry.m_d)/Geometry.n_l;
if M >= 1.1
    k = gamma/sqrt(M^2 - 1);
    A = (1-((0.6 * Geometry.h)/M))*((5*tau)/(6*sqrt(M^2 -1))+ ...
        ((0.5*tau)^2)-((0.7435/(M^2))*((tau*M)^1.6)))*exp(((-1.1952)/ ...
        M)*(cylinder_length-Geometry.bt_l))-(((2.4*(M^4)-4*(M^2-1))* ...
        (((1-Geometry.b_d)/(2*Geometry.bt_l))^2))/(2*(M^2-1)^2))+((2* ...
        ((1-Geometry.b_d)/(2*Geometry.bt_l)))/(sqrt(M^2-1)));
    C_D_BT = ((4*A*tan(boattail_anlge))/k)*((1-exp(-k*Geometry.bt_l))+ ...
        ((2*tan(boattail_anlge))*(((exp(-k*Geometry.bt_l))* ...
        (Geometry.bt_l+k^(-1)))-k^(-1))));
else
    s = 2*((2*((1-Geometry.b_d)/(2*Geometry.bt_l))^2)+((1-Geometry.b_d)...
        /(2*Geometry.bt_l))^3)*(1-exp((-2)*Geometry.bt_l)+(2*((1- ...
        Geometry.b_d)/(2*Geometry.bt_l))*((exp((-2) * Geometry.bt_l)* ...
        (Geometry.bt_l+0.5))-0.5)));
    if M >= 1
        C_D_BT = s*(1.774-9.3*((M^2-1)/(2.4*M^2)));
    else
        C_D_BT = s*(1/(0.564+1250*((M^2-1)/(2.4*M^2))^2));
    end
    
end